import { readFile, writeFile } from "node:fs/promises";
import { createHash } from "node:crypto";
import { fileURLToPath } from "node:url";
import { resolve } from "node:path";
const root = fileURLToPath(new URL("../", import.meta.url));
export const assets = ["index.html", "styles.css", "capture-core.js", "capture.js", "record-format.js",
  "demo-workspace-core.js", "demo-workspace.js", "data/synthetic-index.js", "explore-core.js", "explore.js",
  "pwa.js", "manifest.json", "icons/app-192.png", "icons/app-512.png", "plan-latest/logo-light.png",
  "contracts/record-contract.js", "contracts/demo-service.js", "contracts/fixtures.js", "proposal-demo.js"];
export async function buildWorker() {
  const hash = createHash("sha256");
  const template = (await readFile(resolve(root, "pwa/sw-template.js"), "utf8")).replace(/\r\n?/g, "\n");
  hash.update(template);
  for (const path of assets) {
    const bytes = await readFile(resolve(root, path));
    hash.update(path + "\n");
    hash.update(path.endsWith(".png") ? bytes : bytes.toString("utf8").replace(/\r\n?/g, "\n"));
  }
  const config = { version: hash.digest("hex").slice(0, 24), assets };
  return "/* Generated by pwa/build-worker.mjs. Do not edit. */\nconst PWA_BUILD = " + JSON.stringify(config) + ";\n" + template;
}
if (process.argv[1] && resolve(process.argv[1]) === fileURLToPath(import.meta.url)) {
  const output = await buildWorker();
  const target = resolve(root, "sw.js");
  if (process.argv.includes("--check")) {
    if ((await readFile(target, "utf8")).replace(/\r\n?/g, "\n") !== output) throw new Error("Worker is stale. Run node pwa/build-worker.mjs.");
  } else await writeFile(target, output);
  console.log("Scoped offline worker verified: " + assets.length + " synthetic static assets.");
}
