/* Generated by pwa/build-worker.mjs. Do not edit. */
const PWA_BUILD = {"version":"bbd1c27a22e732d72816e3de","assets":["index.html","styles.css","capture-core.js","capture.js","record-format.js","demo-workspace-core.js","demo-workspace.js","data/synthetic-index.js","explore-core.js","explore.js","pwa.js","manifest.json","icons/app-192.png","icons/app-512.png","plan-latest/logo-light.png"]};
/* Generated configuration precedes this worker. Only reviewed synthetic app assets are cached. */
"use strict";
const SCOPE = new URL(self.registration.scope);
const PREFIX = "labhippo-pwa::" + encodeURIComponent(SCOPE.href) + "::";
const CACHE = PREFIX + PWA_BUILD.version;
const ASSETS = new Set(PWA_BUILD.assets.map(path => new URL(path, SCOPE).href));
const INDEX = new URL("index.html", SCOPE).href;

self.addEventListener("install", event => {
  event.waitUntil((async () => {
    // Fetch every asset successfully before creating the new version's cache.
    const responses = await Promise.all([...ASSETS].map(async url => {
      const response = await fetch(url, { cache: "reload", credentials: "omit" });
      if (!response.ok || response.type === "opaque" || new URL(response.url).origin !== SCOPE.origin) {
        throw new Error("Offline asset unavailable: " + url);
      }
      // Drain each body before waiting for the entire batch; bounded browser connection
      // pools can otherwise stall queued requests while unread responses hold sockets.
      await response.clone().arrayBuffer();
      return [url, response];
    }));
    const cache = await caches.open(CACHE);
    for (const [url, response] of responses) await cache.put(url, response);
    // Never skipWaiting during install: an open page may contain an unsaved draft.
  })());
});
self.addEventListener("activate", event => {
  event.waitUntil((async () => {
    for (const name of await caches.keys()) {
      if (name.startsWith(PREFIX) && name !== CACHE) await caches.delete(name);
    }
    await self.clients.claim();
  })());
});
self.addEventListener("message", event => {
  if (event.data?.type !== "APPLY_BACKED_UP_UPDATE" || !event.source?.url) return;
  const source = new URL(event.source.url);
  if (source.origin === SCOPE.origin && source.pathname.startsWith(SCOPE.pathname)) self.skipWaiting();
});
self.addEventListener("fetch", event => {
  const request = event.request;
  const url = new URL(request.url);
  url.hash = ""; // Record/filter bookmarks address the same reviewed static document.
  if (request.method !== "GET" || url.origin !== SCOPE.origin || url.search ||
      !url.pathname.startsWith(SCOPE.pathname)) return;
  const key = url.href === SCOPE.href ? INDEX : url.href;
  if (!ASSETS.has(key)) return; // Includes every API route, source record and other app.
  event.respondWith((async () => {
    const cached = await caches.match(key, { cacheName: CACHE });
    return cached || fetch(request); // No runtime caching or broader navigation fallback.
  })());
});
